import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "../lib/SessionProvider";
import { ThemeProvider } from "./contexts/themeContext";
import { CssBaseline } from "@mui/material";
import Navbar from "../components/navbar/Navbar";
import ThemeSwitcher from "../components/themeSwitcher/themeSwitcher";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Fast clean service",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <ThemeProvider>
            <CssBaseline />
            <div style={{ position: "relative", minHeight: "100vh" }}>
              <Navbar />
              {children}
              <div
                style={{
                  position: "fixed",
                  bottom: "5rem",
                  right: "6rem",
                }}
              >
                <ThemeSwitcher />
              </div>
            </div>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
