export const packages = [
  {
    id: "subscription-exterior",
    name: "EXTERIOR",
    packages: [
      "Dashboard en vakjes afnemen",
      "Dorpels en deurranden",
      "Matten uitstomen",
      "Ramen en spiegels reinigen",
      "Stoomreiniging Interior globaal",
    ],
    description: "Thorough Care for the Inside, Leaving Your Vehicle Fresh and Clean.",
    totalDuration: "N/A",
    duration: "± 36 min.",
    price: "€ 74.00",
    additionalOptions: [],
    durationOptions: [],
    cleaningFrequencyOptions: [],
  },
  {
    id: "subscription-interior",
    name: "INTERIOR",
    packages: ["Exterior wassen", "Ramen en spiegels reinigen", "Spray wax aanbrengen", "Velgen"],
    description: "Restore the Shine of your Vehicle's Exterior with Premium Detailing.",
    totalDuration: "N/A",
    duration: "± 45 min.",
    price: "€ 94.00",
    additionalOptions: [],
    durationOptions: [],
    cleaningFrequencyOptions: [],
  },
  {
    id: "subscription-combi",
    name: "COMBI",
    packages: ["Interior Package", "Exterior Package", "Complete car care"],
    description: "The Complete Package for Ultimate Interior and Exterior Protection and Shine.",
    totalDuration: "N/A",
    duration: "± 101 min.",
    price: "€ 149.00",
    additionalOptions: [],
    durationOptions: [],
    cleaningFrequencyOptions: [],
  },
];
